### ISSUE TITLE
Aprender a propriedade css position.

### ISSUE THREAD

**Issue by Gilson401** [betoxz15/helloworld#3]
Pesquise nos sites referência a propriedade position.

A propriedade position  aceita sete valores:  static, absolute, fixed, relative, sticky, initial e inherit.
As propriedades mais usadas no desenvolvimento web são: absolute, fixed, relative e sticky.
Entenda cada uma destas 4: absolute, fixed, relative e sticky.
Insira no teu projeto um exemplo de cada uma delas.

**Comment by betoxz15** [comment]
feito conforme o commit o ultimo commit feito
