### ISSUE TITLE
Aprender padding e margin

### ISSUE THREAD

**Issue by Gilson401** [betoxz15/helloworld#4]
Pesquisar o que são as propriedades de estilo padding e margin.
O que cada uma faz?
Qual a diferença de uma para a outra?
Quais são as formas de usar (diferentes formas de colocar valores em cada uma)?
Coloque no seu projeto duas divs para cada propriedade mostrando o efeito que elas aplicam no estilo.

**Comment by betoxz15** [comment]
Bom o com o padding você pode acrescentar espaço diante a borda 

E com a margin você pode dar espaço nos elementos que esta fora dela
