### ISSUE TITLE
Z-index

### ISSUE THREAD

**Issue by Gilson401** [betoxz15/helloworld#8]
Pesquise o z-index.

O que o z index faz ?
Como usar o z-index?
Coloque exemplo no teu projeto mostrando o efeito do z-index.

Dica: o z-index não funciona sozinho. Ele trabalha junto de outra instrução css para poder funcionar. 
Responda as perguntas desta issue nos comentários.

**Comment by betoxz15** [comment]
O z-index sobrepõem os elementos que estão na mesma posição. 
O elemento com maior z-index fica na frente do menor z-index.
Tem que ser usado com umas da position: static , absolute ou fixed
